### ISSUE TITLE
GuitarString.__str__() method produces octave inconsistent with MIDI encoding.

### ISSUE THREAD

**Issue by cwitkowitz** [Perlence/PyGuitarPro#27]
Standard tuning in MIDI would be `[40, 45, 50, 55, 59, 64]`, but the `GuitarString` equivalent of this is `[E3, A3, D4, G4, B4, E5]`.

This is inconsistent with MIDI. 
![image](https://user-images.githubusercontent.com/33099118/147991424-4467090f-4d76-4b13-ab04-53a6e6a790be.png)

I'm not sure if this is intentional, but it could be easily fixed by subtracting 1 from the octave (or 12 from the string value in the `divmod` call).

**Comment by Perlence** [comment]
Hello @cwitkowitz! I think the current numbering is consistent with what we see on the Guitar Pro 5 track properties dialog:

<img src="https://user-images.githubusercontent.com/1044300/148657080-cc49934e-8de7-4f12-9416-4ab0f605b6d0.png" width="663px">

I'm not sure what was the reasoning behind this numbering in GP5. Maybe because guitar is a transposing instrument. For example, the lowest string, E2, is written as E3 in music notation.

In GP6 the octave numbers were changed to be aligned with the MIDI standard (Scientific pitch notation):

![image](https://user-images.githubusercontent.com/1044300/148657222-9d62b233-f4fc-4967-b0d9-9055fbe0d1d7.png)

It does make sense to align GuitarString with the MIDI standard. However, I have to check for compatibility issues.

**Comment by Perlence** [comment]
Thanks, it's a part of v0.9 now.
